In [57]:
import numpy as np

In [58]:
data = np.arange(20, 200, 20)

In [59]:
data

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180])

In [60]:
data.mean()

100.0

In [61]:
sum = data.sum()

In [62]:
sum

900

In [63]:
length = len(data)

In [64]:
sum/length

100.0

In [65]:
data.mean()

100.0

In [66]:
score = np.array([78, 80, 98, 87])
weights = np.array([20, 15, 40, 25])

In [67]:
np.average(score, weights = weights)

88.55

In [68]:
data

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180])

In [69]:
data = data[2:7]

In [70]:
data

array([ 60,  80, 100, 120, 140])

In [71]:
data.mean()

100.0