In [23]:
import numpy as np
from scipy import stats

In [2]:
data = np.arange(20, 200, 20)

In [3]:
data

array([ 20,  40,  60,  80, 100, 120, 140, 160, 180])

In [5]:
np.median(data)

100.0

In [6]:
len(data)

9

In [13]:
x = np.arange(10, 28, 3)

In [14]:
x

array([10, 13, 16, 19, 22, 25])

In [15]:
len(x)

6

In [16]:
np.median(x)

17.5

In [17]:
(16 + 19)/2

17.5

In [25]:
y = np.array([1,3,4,6,1,4,8,0,1,5,1,2,1,41,67,1,3,3,3,3,3,3,3,3])

In [26]:
y

array([ 1,  3,  4,  6,  1,  4,  8,  0,  1,  5,  1,  2,  1, 41, 67,  1,  3,
        3,  3,  3,  3,  3,  3,  3])

In [27]:
stats.mode(y)

ModeResult(mode=array([3]), count=array([9]))